name: pytorch-venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyterthemes
  - lesscpy
  - asn1crypto
  - attrs
  - bleach
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - coverage
  - cryptography
  - cycler
  - cymem
  - cytoolz
  - dbus
  - decorator
  - dill
  - entrypoints
  - expat
  - fontconfig
  - freetype
  - ftfy
  - glib
  - gmp
  - html5lib
  - icu
  - idna
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyterlab
  - jupyterlab_launcher
  - libedit
  - libffi
  - libgfortran-ng
  - libpng
  - libsodium
  - libtiff
  - libxcb
  - libxml2
  - libxslt
  - lxml
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - msgpack-numpy
  - msgpack-python
  - murmurhash
  - nbconvert
  - nbformat
  - ncurses
  - nltk
  - notebook
  - numpy
  - olefile
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pathlib
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - plac
  - pluggy
  - ply
  - preshed
  - prompt_toolkit
  - ptyprocess
  - py
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - pytest
  - python
  - python-dateutil
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - readline
  - regex
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - simplegeneric
  - sip
  - six
  - spacy
  - sqlite
  - statsmodels
  - termcolor
  - terminado
  - testpath
  - thinc
  - tk
  - toolz
  - tornado
  - tqdm
  - traitlets
  - ujson
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - wrapt
  - xz
  - yaml
  - zeromq
  - zlib
  - pytorch
  - torchvision
  - pip:
    - autopep8
    - awscli
    - bcolz
    - beautifulsoup4
    - boto
    - boto3
    - botocore
    - bz2file
    - cliff
    - cmd2
    - colorama
    - configparser
    - cssselect
    - docutils
    - en-core-web-sm
    - fastai
    - feather-format
    - fr-core-news-sm
    - gensim
    - graphviz
    - isoweek
    - jmespath
    - kaggle-cli
    - mechanicalsoup
    - mizani
    - opencv-python
    - palettable
    - pandas-summary
    - pbr
    - plotnine
    - prettytable
    - progressbar2
    - pyarrow
    - pyasn1
    - pycodestyle
    - pyperclip
    - python-utils
    - rsa
    - s3transfer
    - sklearn-pandas
    - smart-open
    - stevedore
    - torch
    - torchtext
